services:
  - type: web
    name: flask-api
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false  # You still set the value from the dashboard
